### ISSUE TITLE
Phase 2 recognition erroring

### ISSUE THREAD

**Issue by phit** [sk89q/HeyVictoria#3]
So I took the time to try this out, really cool idea. But I can't seem to get the recognition part 2 to work, windows 8.1 - SpeechRecognition-3.1.0 - pocketsphinx-0.0.5

```
(heyvictoria.listener) INFO: Found key phrase!
(heyvictoria.listener) INFO: Phase 2 recording complete; now recognizing...
Exception in thread Thread-5:
Traceback (most recent call last):
  File "F:\Python27\lib\threading.py", line 530, in __bootstrap_inner
    self.run()
  File "F:\HeyVictoria\HeyVictoria\listen_server\heyvictoria\listener.py", line 99, in run
    self._process(buf)
  File "F:\HeyVictoria\HeyVictoria\listen_server\heyvictoria\listener.py", line 124, in _process
    self._recognize()
  File "F:\HeyVictoria\HeyVictoria\listen_server\heyvictoria\listener.py", line 158, in _recognize
    flac = self.recognizer.samples_to_flac(FakeAudioSource(self.sample_width, self.sample_rate, self.channels), frame_data)
AttributeError: 'Recognizer' object has no attribute 'samples_to_flac'
```

Any help is really appreciated!

**Comment by sk89q** [comment]
I think you need SpeechRecognition 2.x.

**Comment by phit** [comment]
yup, that was it. thanks!
